### ISSUE TITLE
Error: SignatureFieldComponent class SignatureFieldComponent - inline template:0:0 caused by: sp is not a constructor

### ISSUE THREAD

**Issue by teresahoes** [lathonez/angular2-signaturepad-demo#4]
Hello - i am trying to implement your demo and i get this error upon running. i've tried using this demo as well as the simpler version on the main git hub page and get the same error. 

SignatureFieldComponent class SignatureFieldComponent - inline template:0:0 caused by: sp is not a constructor
Error: Error in ./SignatureFieldComponent class SignatureFieldComponent - inline template:0:0 caused by: sp is not a constructor

**Comment by lathonez** [comment]
Hi Teresa,

This came from a bad version of `angular2-signature-pad`: https://github.com/wulfsolter/angular2-signaturepad/issues/33

If you fully remove `node_modules` and re-install them you should be fine. 2.3.0 is the bad version, you should have 2.4.0.

Thanks,

Stephen

**Comment by lathonez** [comment]
Resolved as per the above
